// packages/finicky-ui/src/components/LogContent.tsx
import type { LogEntry } from "../types";
import { formatLogEntry } from "../utils/text";
import styles from "./LogContent.module.css";

interface Props {
  messageBuffer: LogEntry[];
  showDebug: boolean;
}

const levelClassMap: Record<string, string> = {
  error: styles.logLevelError,
  warn: styles.logLevelWarn,
  debug: styles.logLevelDebug,
};

export function LogContent({ messageBuffer, showDebug }: Props) {
  return (
    <ol className={styles.logContent}>
      {messageBuffer
        .filter((entry) => showDebug || entry.level.toLowerCase() !== "debug")
        .map((entry, i) => (
          <li key={i} className={styles.logEntry}>
            <span className={styles.logTime} title={entry.time}>
              {new Date(entry.time).toLocaleTimeString()}
            </span>
            <div className={`${styles.logMessage} ${levelClassMap[entry.level.toLowerCase()] ?? ""}`}>
              {formatLogEntry(entry).map((part, j) =>
                part.type === "url" ? (
                  <a key={j} href={part.content} target="_blank" rel="noopener noreferrer">
                    {part.content}
                  </a>
                ) : (
                  <span key={j}>{part.content}</span>
                )
              )}
            </div>
          </li>
        ))}
    </ol>
  );
}

// packages/finicky-ui/src/components/LogContent.svelte
<script lang="ts">
  import type { LogEntry } from "../types";
  import { formatLogEntry } from "../utils/text";

  export let messageBuffer: LogEntry[] = [];
  export let showDebug = true;

  let logContent: HTMLElement;
</script>

<ol class="log-content" bind:this={logContent}>
  {#each messageBuffer as entry}
    {#if showDebug || entry.level.toLowerCase() !== "debug"}
      <li class="log-entry">
        <span class="log-time" title={entry.time}>
          {new Date(entry.time).toLocaleTimeString()}
        </span>
        <div class="log-message log-level-{entry.level.toLowerCase()}">
          {#each formatLogEntry(entry) as part}
            {#if part.type === "url"}
              <a href={part.content} target="_blank" rel="noopener noreferrer"
                >{part.content}</a
              >
            {:else}
              {part.content}
            {/if}
          {/each}
        </div>
      </li>
    {/if}
  {/each}
</ol>

<style>
  .log-content {
    list-style: none;
    margin: 0;
    padding: 0;
    overflow-y: auto;
    font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas,
      monospace;
    line-height: 1.5;
    color: var(--text-primary);
    flex: 1;
    overflow: auto;
  }

  .log-entry {
    display: flex;
    justify-content: flex-start;
    gap: 1em;
    margin-bottom: 8px;
    align-items: flex-start;
  }

  .log-time {
    color: var(--text-secondary);
    white-space: nowrap;
    font-size: 0.85em;
    opacity: 0.8;
  }

  .log-message {
    flex-grow: 1;
    white-space: pre-wrap;
    word-break: break-word;
    font-size: 0.95em;
  }

  .log-level-error {
    color: var(--log-error);
  }

  .log-level-warn {
    color: var(--log-warning);
  }

  .log-level-debug {
    color: var(--log-debug);
  }

  :global(.log-message a) {
    color: inherit;
    text-decoration: underline;
    text-decoration-style: dotted;
    opacity: 0.9;
  }

  :global(.log-message a:hover) {
    text-decoration-style: solid;
    opacity: 1;
  }
</style>
